version: '3'

services:
  demo-graph:
    image: sisinflabpoliba/demo-graph
    tty: true
    stdin_open: true
    command: CUBLAS_WORKSPACE_CONFIG=:16:8 python3.8 start_experiments.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./results:/Graph-Demo/results
