experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
  dataset: amazon_music
  top_k: 50
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [Recall, Precision, nDCG, EPC, EFD, Gini, SEntropy]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.UltraGCN:
      meta:
        hyper_max_evals: 40
        hyper_opt_alg: tpe
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
      lr: [loguniform, -9.210340372, -5.298317367]
      epochs: 400
      factors: 64
      batch_size: 1024
      g: [loguniform, -9.210340372, 6.90775527898]
      l: [loguniform, -9.21034037198, 1.2527629685]
      w1: 1e-7
      w2: 1.0
      w3: 1e-7
      w4: 1.0
      ii_n_n: 10
      n_n: 300
      n_w: 300.0
      s_s_p: False
      i_w: 1e-4
      seed: 123
      early_stopping:
        patience: 10
        monitor: Recall@20
        mode: auto
        verbose: True
